### PR TITLE
Added travis file

### LINKED ISSUE #7: Automated tests with Travis
Add automatic tests with Travis when pushing to any branch.

### PR DESCRIPTION
**Pull request by surajnarwade**
Updated required files
Fixes #7

### CODE REVIEW

**Comment by jsh2134** [comment]
I created a new branch called travis and changed your pull request base branch to that. 

there were some merge conflicts with your file so I merged, please fetch the latest.

**Comment by jsh2134** [comment]
also if you want to test your commits on travis before making a PR you can do it by signing up your fork. Travis is free for public repos https://travis-ci.org/

**Comment by jsh2134** [comment]
looks like tests passed btw. but then the py2.7 build failed because coveralls maybe? i removed it just now so maybe it will work

**Comment by surajnarwade** [comment]
if everything is okay, merge it then

**Comment by jsh2134** [comment]
merged in via

**Pull request closed without merging**
